name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      with:
        ACCESS_TOKEN: ${{ secrets.deploy }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install --registry=https://registry.npm.taobao.org && npm run docs:build
